async (page) => {
  await page.setViewportSize({ width: 1280, height: 900 })
  const assert = (condition, message) => { if (!condition) throw new Error(message) }
  const editor = page.getByRole('textbox', { name: 'Contenu Markdown' })
  const setText = async text => { await editor.focus(); await editor.press('ControlOrMeta+a'); await page.keyboard.insertText(text); await page.locator('#print-document[aria-busy="true"]').waitFor({ state: 'attached' }) }
  const editorText = () => editor.evaluate(element => Array.from(element.querySelectorAll('.cm-line')).map(line => line.textContent).join('\n'))
  const saved = () => page.getByText('Enregistré dans ce navigateur', { exact: true }).waitFor()
  const exportButton = () => page.getByRole('button', { name: 'Exporter en PDF', exact: true })
  await page.locator('input[webkitdirectory]').setInputFiles('tests/fixtures/workspace')
  await page.getByRole('combobox', { name: 'Document Markdown à afficher' }).waitFor()
  await setText('# A modifié\n\n![Image](images/test.svg)')
  await saved()
  await page.getByRole('combobox', { name: 'Document Markdown à afficher' }).selectOption('b.markdown')
  await setText('# B modifié')
  await saved()
  await page.reload()
  await editor.waitFor()
  assert(await editorText() === '# B modifié', 'Active document not restored')
  await page.getByRole('combobox', { name: 'Document Markdown à afficher' }).selectOption('a.md')
  assert((await editorText()).includes('A modifié'), 'Other document edits lost')
  await page.getByText('Aperçu à jour', { exact: true }).waitFor()
  assert(await page.locator('article img').evaluate(img => img.naturalWidth > 0 && img.src.startsWith('blob:')), 'Image not restored')
  const downloaded = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Télécharger .md' }).click()
  const download = await downloaded
  assert(download.suggestedFilename() === 'a.md', 'Download filename wrong')
  const stream = await download.createReadStream()
  const chunks = []
  for await (const chunk of stream) chunks.push(chunk)
  assert(chunks.map(chunk => chunk.toString()).join('').includes('A modifié'), 'Download content wrong')
  await page.evaluate(() => { window.printCalls = 0; window.print = () => { window.printCalls++ } })
  await setText('# Missing\n\n![Missing](absent.png)')
  await exportButton().click()
  await page.locator('.export-error').waitFor()
  assert(await page.evaluate(() => window.printCalls) === 0, 'Printed with missing image')
  await setText('```mermaid\ninvalid diagram syntax\n```')
  await exportButton().click()
  await page.getByText('Le diagramme Mermaid contient une erreur.', { exact: true }).waitFor()
  await exportButton().waitFor()
  assert(await page.evaluate(() => window.printCalls) === 0, 'Printed invalid Mermaid')
  await setText('# Dernière version\n\n```mermaid\nflowchart LR\nA --> B\n```')
  await exportButton().click()
  await page.waitForFunction(() => window.printCalls === 1)
  assert(await page.locator('article svg').count() === 1, 'Diagram missing during export')
  await page.getByRole('combobox', { name: /^Format/ }).selectOption('Letter')
  await setText('# Rapport long\n\n' + 'Texte de contrôle. '.repeat(6000))
  await page.getByText('Aperçu à jour', { exact: true }).waitFor()
  await page.emulateMedia({ media: 'print' })
  assert(await page.locator('#print-document article').first().evaluate(el => getComputedStyle(el).paddingTop) === '0px', 'Duplicate print margins')
  await page.pdf({ path: 'output/playwright/rapport-long.pdf', preferCSSPageSize: true })
  await page.emulateMedia({ media: null })
  await page.setViewportSize({ width: 390, height: 844 })
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile page overflows')
  await page.screenshot({ path: 'output/playwright/mobile.png' })
  await page.setViewportSize({ width: 1280, height: 900 })
  await saved()
  await page.evaluate(() => {
    window.originalTransaction = IDBDatabase.prototype.transaction
    IDBDatabase.prototype.transaction = function (...args) {
      if (args[1] === 'readwrite') throw new DOMException('Quota', 'QuotaExceededError')
      return window.originalTransaction.apply(this, args)
    }
  })
  try {
    await setText('# Sauvegarde impossible')
    await page.getByText('Échec de sauvegarde — téléchargez votre Markdown', { exact: true }).waitFor()
  } finally {
    await page.evaluate(() => { IDBDatabase.prototype.transaction = window.originalTransaction })
  }
  await page.locator('input[type=file]:not([webkitdirectory])').setInputFiles('tests/fixtures/workspace/b.markdown')
  await saved()
  await page.reload()
  await editor.waitFor()
  assert(await editorText() === '# Document B\n', '.markdown import failed')
  assert(await page.getByTitle('b.markdown', { exact: true }).count() === 1, 'Single filename not restored')
  console.log('PASS: workspace restoration, images, download, blocked exports, latest Mermaid, multipage PDF')
}
