async (page) => {
  const assert = (value, message) => { if (!value) throw new Error(message) }
  const editor = page.getByRole('textbox', { name: 'Contenu Markdown' })
  await editor.waitFor()
  await page.evaluate(() => { window.__prints = 0; window.print = () => { window.__prints++ } })
  await editor.focus()
  await editor.press('ControlOrMeta+a')
  await page.keyboard.insertText('# Titre\n\n![absente](images/absente.png)\n\n```mermaid\nflowchart TD\n A --> \n```')
  await page.locator('#print-document[aria-busy="true"]').waitFor({ state: 'attached' })
  const alert = page.locator('.pagination-error')
  await alert.waitFor()
  const text = await alert.textContent()
  assert(text.includes('images/absente.png'), 'Missing image path not reported: ' + text)
  assert(text.includes('Diagrammes Mermaid'), 'Mermaid failure not reported: ' + text)
  await page.keyboard.press('ControlOrMeta+p')
  await page.locator('.export-error').waitFor()
  assert(await page.evaluate(() => window.__prints) === 0, 'Print started despite errors')
  await editor.focus()
  await editor.press('ControlOrMeta+a')
  await page.keyboard.insertText('# Propre')
  await page.getByText('Aperçu à jour', { exact: true }).waitFor()
  await page.keyboard.press('ControlOrMeta+p')
  await page.waitForFunction(() => window.__prints === 1)
  console.log('PASS: precise export errors, Ctrl+P gated by readiness')
}
